services:
  db:
    image: postgres:15
    container_name: etnair_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: etnair_user
      POSTGRES_PASSWORD: etnair_pass
      POSTGRES_DB: etnair_db
    volumes:
      - etnair_db_data:/var/lib/postgresql/data
      - ./back/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etnair_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etnair_user -d etnair_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  back:
    build: ./back/api
    container_name: etnair_api
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://etnair_user:etnair_pass@db:5432/etnair_db

    volumes:
      - ./back/api:/app
    working_dir: /app

    depends_on:
      db:
        condition: service_healthy
    networks:
      - etnair_network

  front:
    build: ./front
    container_name: etnair_front
    ports:
      - "8080:80"
    networks:
      - etnair_network

networks:
  etnair_network:
    driver: bridge

volumes:
  etnair_db_data:
